name: Testing Inbuil Actions
on: workflow_dispatch
jobs:
   testjob:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout the code
       uses: actions/checkout@v6
     - name: Disply List of files
       run: |
           ls -l 
     - name: Docker Login
       uses: docker/login-action@v4
       with:
         username: svreddyaws56 
         password: ${{ secrets.DOCKER_REG_PASSWD }} 
     - name: Docker Build & Push 
       uses: docker/build-push-action@v7
       with:
          context: .
          tags: docker.io/svreddyaws56/testimagex
          push: true 
     - name: Deploy Application
       uses: appleboy/ssh-action@v1
       with:
         host: '13.203.159.71'
         username: ubuntu
         key: ${{ secrets.XSERVERPRVKEY }}
         script: |
            whoami
            docker run -d docker.io/svreddyaws56/testimagex
            docker ps -a 
            
         
                    