name: Testing Inbuil Actions
on: workflow_dispatch
jobs:
   testjob:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout the code
       uses: actions/checkout@v6
     - name: Disply List of files
       run: |
           ls -l 
     - name: Docker Login
       uses: docker/login-action@v4
       with:
         username: svreddyaws56 
         password: ${{ secrets.DOCKER_REG_PASSWD }}         