name: Workflow-3
on: workflow_dispatch
jobs:
   Linux-Job1:
     runs-on: ubuntu-latest
     env:
       name: Sheshivardhan
       Rel: V1.10
     steps:
     - name: Step1
       env:
         DB_USER: Scott       
       run: |
          date
          echo "This i Test Step"
          echo "Name Value is: $name and Rel Verstion $Rel"
          echo "DB USSER $DB_USER"          
          
     - name: Step2
       run: | 
         echo "Step2"
         echo "Name Value is: $name and Rel Verstion $Rel"
         echo "DB USSER $DB_USER"         
   