name: Workflow-3
on: workflow_dispatch
jobs:
   Linux-Job1:
     runs-on: ubuntu-latest
     env:
       name: Sheshivardhan
       Rel: V1.10
     steps:
     - name: Execute Multipple Cmd
       run: |
          date
          echo "This i Test Step"
          echo "Name Value is: $name and Rel Verstion $Rel" 
     - name: Checking Docker Verstion
       run: | 
         echo "Step2"
         echo "Name Value is: $name and Rel Verstion $Rel"  
   Linux-Job2:
     needs: Linux-Job1
     runs-on: ubuntu-latest
     steps:
     - name: Current system Date
       run: |
         echo "in Job2: Name Value is: $name and Rel Verstion $Rel"