name: Event filters
on: 
  push:
    branches:
    - B1
jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
     - name: Print MSg
       run: |
          echo "Hello Wolrd"	   
          
          
          
          