name: Build Docker Image
on: workflow_dispatch
jobs:
  Build_Image:
    runs-on: ubuntu-latest
    steps:
    - name: Downlond Code
      run: |
        git clone https://github.com/sreddy2809/MYCICD.git
        ls -l
    - name: ImageBuild
      run: |
         docker info

