name: Build Docker Image
on: workflow_dispatch
jobs:
  Build_Image:
    env:
      image_name: docker.io/svreddyaws56/testimage1 
    runs-on: ubuntu-latest
    steps:
    - name: Downlond Code
      run: |
        git clone https://github.com/sreddy2809/MYCICD.git
        ls -l
    - name: ImageBuild
      run: |
         docker info
         cd MYCICD
         docker build -t $image_name .
         docker images
    - name: Image Push 
      run: |
         docker login -u svreddyaws56 -p ${{ secrets.DOCKER_REG_PASSWD }}
         docker push $image_name  
    - name: Deploy into Xserver
    
      run: |
        echo "${{ secrets.XSERVERPRVKEY }}" > key1
        ls -l 
        chmod 600 key1
        ls -l
        ssh -i key1 -o StrictHostKeyChecking=no ubuntu@13.203.159.71 docker run -d $image_name
        
