name: Wf for Secrets
on: workflow_dispatch
env:
  abc: ${{ secrets.MYPASSWD }} 
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - name: Print My secrets
      run: |
        echo Print abc env
        echo $abc