name: Wf for Secrets
on: workflow_dispatch
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - name: Print My secrets
      run: |
        echo Print Secrets
        echo ${{ secrets.MYPASSWD }}